[package]
name = "becnhv2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.10", features = ["derive"] }
env_logger = "0.11.4"
git2 = "0.19.0"
log = "0.4.22"
